[versions]
kotlin = "2.0.10" # https://github.com/JetBrains/kotlin/releases

jvmTarget = "17"
androidCompileSDK = "34"
androidMinimalSDK = "28"
androidTargetSDK = "34"
tammy = "1.0.0"
tammyVersionCode = "1"
appName = "Tammy"

trixnityMessenger = "2.2.3-DEV-23200989" # https://gitlab.com/connect2x/trixnity-messenger/trixnity-messenger/-/packages

composeMultiplatform = "1.7.0-beta02" # https://github.com/JetBrains/compose-multiplatform/releases
aboutLibraries = "11.2.1" # https://github.com/mikepenz/AboutLibraries/releases
downloadGradlePlugin = "5.6.0" # https://github.com/michel-kraemer/gradle-download-task/releases
copyWebpackPlugin = "12.0.2" # https://github.com/webpack-contrib/copy-webpack-plugin/releases
logback = "1.5.8" # https://github.com/qos-ch/logback/tags
slf4j = "2.0.15" # https://github.com/qos-ch/slf4j/tags
kotlinxCoroutines = "1.9.0" # https://github.com/Kotlin/kotlinx.coroutines/releases

activity = "1.9.2" # https://developer.android.com/jetpack/androidx/releases/activity
logbackAndroid = "3.0.0" # https://github.com/tony19/logback-android/releases
workManager = "2.9.1" # https://developer.android.com/jetpack/androidx/releases/work
liveData = "2.8.6" # https://developer.android.com/jetpack/androidx/releases/lifecycle
appcompat = "1.7.0" # https://developer.android.com/jetpack/androidx/releases/appcompat
firebase = "33.3.0" # https://firebase.google.com/support/release-notes/android

[libraries]
trixnity-messenger = { module = "de.connect2x:trixnity-messenger", version.ref = "trixnityMessenger" }
messenger-compose-view = { module = "de.connect2x:trixnity-messenger-compose-view", version.ref = "trixnityMessenger" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logbackAndroid" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "liveData" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx", version = "" }

kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }

[bundles]
android-common = ["androidx-appcompat", "androidx-work-runtime-ktx", "androidx-lifecycle-livedata-ktx", "androidx-activity-compose", "logback-android"]

[plugins]
# ui
aboutlibraries-plugin = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
download-plugin = { id = "de.undercouch.download", version.ref = "downloadGradlePlugin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
